### ISSUE TITLE
Microphone access asked when proposing new product

### ISSUE THREAD

**Issue by RaymondWillems** [WirMarkt/wirmarkt-app#16]
When proposing a new product, the Android app is asking for microphone access.

**Comment by fabiangebert** [comment]
Should be fixed now.

**Comment by fabiangebert** [comment]
Yes, play store version is older than the one on github.

**Comment by RaymondWillems** [comment]
Alpha 7 doesnt ask for mic access, but fails starting the camera. "Failed to initialize camera"

**Comment by fabiangebert** [comment]
Yes, I found the bug. Will fix soon.

**Comment by fabiangebert** [comment]
Alpha Preview 8 should fix this.
