### ISSUE TITLE
Portrait mode design bugs

### ISSUE THREAD

**Issue by RaymondWillems** [WirMarkt/wirmarkt-app#19]
Main screen (membership) and Impact screen have no portrait mode.

**Comment by fabiangebert** [comment]
should be fixed now with release https://github.com/WirMarkt/wirmarkt-app/releases/tag/preview-alpha-1

**Comment by RaymondWillems** [comment]
Looks better!

Still the icons could be smaller, three columns for membership and two cols for impact (better in new issue).
